import Prism from 'prismjs';
import 'prismjs/components/prism-sql';

// Extend the built-in SQL grammar with SQLite functions Prism misses
Prism.languages.sql['function'] = {
  pattern: /\b(?:ABS|AVG|CAST|CHAR|COALESCE|COUNT|DATE|DATETIME|GROUP_CONCAT|HEX|IFNULL|IIF|INSTR|JULIANDAY|LENGTH|LIKE|LOWER|LTRIM|MAX|MIN|NULLIF|PRINTF|QUOTE|RANDOM|RANDOMBLOB|REPLACE|ROUND|RTRIM|SIGN|SOUNDEX|STRFTIME|SUBSTR|SUBSTRING|SUM|TIME|TOTAL|TRIM|TYPEOF|UNICODE|UPPER|ZEROBLOB|ROW_NUMBER|RANK|DENSE_RANK|NTILE|LAG|LEAD|FIRST_VALUE|LAST_VALUE|NTH_VALUE|PERCENT_RANK|CUME_DIST)\b(?=\s*\()/i,
};

export default Prism;
